/// GENERATED by scripts/build-nav-icons.ts from brand/icons. Do not edit;
/// change the SVGs and run `npm run build:nav-icons`.
///
/// The stroke is currentColor, so these follow the surrounding text colour.
/// The teal and cream accents are the brand's own and stay fixed.

type IconProps = { className?: string };

const DEFAULT = "h-5 w-5";

export function BeenIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <circle cx="32" cy="32" r="23" stroke="currentColor" strokeWidth="3"/><path d="M10 31h44M32 9c7 7 10 15 10 23s-3 16-10 23M32 9c-7 7-10 15-10 23s3 16 10 23" stroke="currentColor" strokeWidth="2.5"/><path d="M17 18c5 4 10 5 15 4 5-1 10-1 15 3M18 46c5-3 10-4 14-3 5 1 10 0 15-3" stroke="currentColor" strokeWidth="2"/>
    </svg>
  );
}

export function FeedIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <rect x="13" y="10" width="38" height="44" rx="6" stroke="currentColor" strokeWidth="3"/><circle cx="22" cy="20" r="3.5" fill="#14B8A6" stroke="currentColor" strokeWidth="2"/><path d="M29 20h10" stroke="currentColor" strokeWidth="2.5"/><path d="m18 41 9-10 8 8 5-5 7 7" stroke="currentColor" strokeWidth="3"/><circle cx="43" cy="25" r="3" fill="#F2A07B"/><path d="M20 47h22" stroke="currentColor" strokeWidth="2.5"/>
    </svg>
  );
}

export function JournalIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M10 14c0-3 2-5 5-5h15c4 0 7 2 8 5v38c-2-2-5-3-8-3H15c-3 0-5-2-5-5V14Z" stroke="currentColor" strokeWidth="3"/><path d="M54 14c0-3-2-5-5-5H34c-4 0-7 2-8 5v38c2-2 5-3 8-3h15c3 0 5-2 5-5V14Z" stroke="currentColor" strokeWidth="3"/><path d="M17 22h10M17 29h10M17 36h8" stroke="currentColor" strokeWidth="2.5"/><rect x="37" y="22" width="11" height="13" rx="1" stroke="currentColor" strokeWidth="2.5"/><path d="m39 33 3-4 2 2 4-5" stroke="#A7B49E" strokeWidth="2.2"/><circle cx="46" cy="24" r="2" fill="#F2A07B"/>
    </svg>
  );
}

export function MapIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M8 16 22 10l20 8 14-6v36l-14 6-20-8-14 6V16Z" stroke="currentColor" strokeWidth="3"/><path d="M22 10v36M42 18v36" stroke="currentColor" strokeWidth="3"/><path d="M18 36c6 4 10-2 16-2 7 0 8 7 14 4" stroke="currentColor" strokeWidth="2.5" strokeDasharray="4 5"/><path d="M50 8c-6 0-11 5-11 11 0 8 11 19 11 19s11-11 11-19C61 13 56 8 50 8Z" fill="#14B8A6" stroke="currentColor" strokeWidth="3"/><circle cx="50" cy="19" r="4" fill="#F4EDE1" stroke="currentColor" strokeWidth="2"/>
    </svg>
  );
}

export function PeopleIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <circle cx="24" cy="22" r="7" stroke="currentColor" strokeWidth="3"/><path d="M12 47c1-10 6-15 12-15s11 5 12 15H12Z" stroke="currentColor" strokeWidth="3"/><circle cx="43" cy="26" r="5" fill="#A7B49E" fillOpacity=".75" stroke="currentColor" strokeWidth="2.5"/><path d="M36 47c1-7 4-11 9-11s8 4 9 11H36Z" fill="#A7B49E" fillOpacity=".4" stroke="currentColor" strokeWidth="2.5"/>
    </svg>
  );
}

export function PlacesIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M31 11v42" stroke="currentColor" strokeWidth="3"/><path d="M17 17h28l7 7-7 7H17V17Z" fill="#14B8A6" fillOpacity=".55" stroke="currentColor" strokeWidth="3"/><path d="M47 36H19l-7 7 7 7h28V36Z" fill="#F4EDE1" stroke="currentColor" strokeWidth="3"/>
    </svg>
  );
}

export function SignOutIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M34 12H18c-3 0-5 2-5 5v30c0 3 2 5 5 5h16" stroke="currentColor" strokeWidth="3"/><path d="M30 32h24" stroke="#14B8A6" strokeWidth="4"/><path d="m47 24 8 8-8 8" stroke="#14B8A6" strokeWidth="4"/>
    </svg>
  );
}

export function TripsIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <rect x="14" y="18" width="36" height="34" rx="6" stroke="currentColor" strokeWidth="3"/><path d="M24 18v-5c0-2 2-4 4-4h8c2 0 4 2 4 4v5" stroke="currentColor" strokeWidth="3"/><path d="M20 18v34M44 18v34" stroke="currentColor" strokeWidth="2.5"/><circle cx="27" cy="32" r="4" fill="#14B8A6"/><path d="m34 38 8-5 5 7-8 5-5-7Z" fill="#F4EDE1"/>
    </svg>
  );
}

export function WhosUsingRoavaIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <circle cx="32" cy="32" r="24" fill="#F4EDE1"/><circle cx="32" cy="24" r="6" fill="currentColor"/><path d="M22 46c1-9 5-14 10-14s9 5 10 14" fill="currentColor"/><circle cx="18" cy="29" r="5" fill="#14B8A6"/><path d="M10 46c1-7 4-11 8-11s7 4 8 11" fill="#14B8A6"/><circle cx="46" cy="29" r="5" fill="#F2A07B"/><path d="M38 46c1-7 4-11 8-11s7 4 8 11" fill="#F2A07B"/>
    </svg>
  );
}

export function YourProfileIcon({ className }: IconProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <circle cx="32" cy="32" r="23" stroke="currentColor" strokeWidth="3"/><circle cx="32" cy="25" r="7" fill="currentColor"/><path d="M18 48c2-9 7-14 14-14s12 5 14 14" fill="#A7B49E" fillOpacity=".7" stroke="currentColor" strokeWidth="3"/>
    </svg>
  );
}
