/// Turns the brand SVGs into one React module.
///
/// Inline rather than <img>: an inline SVG inherits colour, which is the whole
/// reason to prefer vectors here. The dark stroke becomes currentColor so the
/// icons follow the theme — navy on the light page, cream on the dark one, teal
/// when a tab is active — instead of being fixed-colour pictures that vanish
/// against a dark background. The teal and cream accents stay, since those are
/// the brand's, not the interface's.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";

const SOURCE_DIR = "brand/icons";
const OUT = "src/components/nav-icons.tsx";

/// The stroke colour used throughout the set.
const INK = /#0F3D34/gi;

/// SVG attributes are hyphenated; JSX wants them camelCased. Anything not
/// listed here would silently become an unknown prop and be dropped.
const ATTRS: Record<string, string> = {
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-dasharray": "strokeDasharray",
  "stroke-miterlimit": "strokeMiterlimit",
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
  "stroke-opacity": "strokeOpacity",
  "fill-opacity": "fillOpacity",
};

function componentName(file: string) {
  return (
    file
      .replace(/\.svg$/, "")
      .split(/[-_]/)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("") + "Icon"
  );
}

function toJsx(svg: string) {
  const body = svg
    .replace(/<\?xml[^>]*\?>/g, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .trim();

  // Keep only what is inside <svg>, so the wrapper below controls sizing.
  const inner = body.replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  const viewBox = /viewBox="([^"]+)"/.exec(body)?.[1] ?? "0 0 64 64";

  let jsx = inner;
  for (const [from, to] of Object.entries(ATTRS)) {
    jsx = jsx.replaceAll(`${from}=`, `${to}=`);
  }
  jsx = jsx.replace(INK, "currentColor");

  return { jsx, viewBox };
}

const files = readdirSync(SOURCE_DIR).filter((f) => f.endsWith(".svg")).sort();

const parts = files.map((file) => {
  const { jsx, viewBox } = toJsx(readFileSync(`${SOURCE_DIR}/${file}`, "utf8"));
  return `export function ${componentName(file)}({ className }: IconProps) {
  return (
    <svg
      viewBox="${viewBox}"
      className={className ?? DEFAULT}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      ${jsx}
    </svg>
  );
}`;
});

writeFileSync(
  OUT,
  `/// GENERATED by scripts/build-nav-icons.ts from ${SOURCE_DIR}. Do not edit;
/// change the SVGs and run \`npm run build:nav-icons\`.
///
/// The stroke is currentColor, so these follow the surrounding text colour.
/// The teal and cream accents are the brand's own and stay fixed.

type IconProps = { className?: string };

const DEFAULT = "h-5 w-5";

${parts.join("\n\n")}
`,
);

console.log(`  wrote ${OUT} with ${files.length} icons:`);
console.log("  " + files.map((f) => componentName(f)).join(", "));
