/// The same brand SVGs as the website, emitted for React Native.
///
/// react-native-svg needs real components rather than markup, and every
/// attribute camelCased — an unrecognised prop is simply ignored, so a missed
/// conversion shows up as an icon drawn without its stroke rather than as an
/// error.
///
/// The stroke becomes a `color` prop, defaulting to the theme's ink, so a tab
/// can tint its icon the same way the website does.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const SOURCE_DIR = "brand/icons";
const OUT = "mobile/src/components/nav-icons.tsx";
const INK = /#0F3D34/gi;

const ELEMENTS: Record<string, string> = { path: "Path", circle: "Circle", rect: "Rect" };

const ATTRS: Record<string, string> = {
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-dasharray": "strokeDasharray",
  "fill-opacity": "fillOpacity",
  "stroke-opacity": "strokeOpacity",
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
};

function componentName(file: string) {
  return (
    file
      .replace(/\.svg$/, "")
      .split(/[-_]/)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("") + "Icon"
  );
}

function convert(svg: string) {
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] ?? "0 0 64 64";
  let inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>[\s\S]*$/, "");

  for (const [from, to] of Object.entries(ATTRS)) inner = inner.replaceAll(`${from}=`, `${to}=`);
  for (const [from, to] of Object.entries(ELEMENTS)) {
    inner = inner.replaceAll(`<${from} `, `<${to} `).replaceAll(`</${from}>`, `</${to}>`);
  }
  // The one colour that follows the theme; the teal and cream accents do not.
  inner = inner.replace(INK, "{color}");
  // JSX needs braces around the interpolated value, not quotes.
  inner = inner.replace(/"{color}"/g, "{color}");

  const used = new Set<string>();
  for (const tag of Object.values(ELEMENTS)) {
    if (inner.includes(`<${tag} `)) used.add(tag);
  }
  return { inner: inner.trim(), viewBox, used };
}

const files = readdirSync(SOURCE_DIR).filter((f) => f.endsWith(".svg")).sort();
const allUsed = new Set<string>(["Svg"]);
const parts: string[] = [];

for (const file of files) {
  const { inner, viewBox, used } = convert(readFileSync(`${SOURCE_DIR}/${file}`, "utf8"));
  used.forEach((u) => allUsed.add(u));
  parts.push(`export function ${componentName(file)}({ size = 24, color = INK }: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="${viewBox}" fill="none">
      ${inner}
    </Svg>
  );
}`);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `/// GENERATED by scripts/build-native-icons.ts from ${SOURCE_DIR}. Do not edit;
/// change the SVGs and run \`npm run build:native-icons\`.
///
/// Shares its source with the website's icons, so the two cannot drift.
import type { ColorValue } from "react-native";
import { ${[...allUsed].sort().join(", ")} } from "react-native-svg";
import { colors } from "@/lib/theme";

const INK = colors.light.ink;

/// ColorValue rather than string: navigation hands its icons the tab's colour
/// in that form, and react-native-svg accepts it directly.
type IconProps = { size?: number; color?: ColorValue };

${parts.join("\n\n")}
`,
);

console.log(`  wrote ${OUT}`);
console.log(`  elements used: ${[...allUsed].sort().join(", ")}`);
console.log(`  icons: ${files.map(componentName).join(", ")}`);
